---
vault_auth_approle.settings:
  type: config_object
  label: 'Vault AppRole Auth Provider Settings'
  mapping:
    role_id:
      type: string
      label: 'AppRole ID'
    secret_key_id:
      type: string
      label: 'Key Entity ID'
